import { commentsConfig } from './config.js';
const root=document.getElementById('comments');
const en=document.documentElement.lang==='en';
const strings=en?{
 pendingPrivacy:'Visible only to you and the moderator',settingsTitle:'Discussion settings',backupTitle:'Private backups',dangerTitle:'Destructive and access actions',readOnly:'New comments are temporarily disabled.',visibility:'Discussion visibility',visible:'Visible',hiddenDiscussion:'Hidden',posting:'Allow new comments and replies',confirmSettings:'Change discussion settings? Existing comment statuses will not change.',disabled:'Comments are not enabled yet.',loading:'Loading comments…',empty:'No published comments yet.',error:'Comments are temporarily unavailable. The article remains accessible. Reload the page to try again; check your submissions before posting again.',
 login:'Sign in with Google',logout:'Sign out',cancelled:'Sign-in was cancelled.',post:'Send comment',text:'Comment text',notice:'Comments become public after approval. Do not post patient data or sensitive operational information.',hidden:'Hidden',pending:'Awaiting approval',sent:'Your comment is awaiting approval.',published:'Your comment was published.',reply:'Reply',cancelReply:'Cancel reply',replyTo:'Reply to',more:'Load more',mine:'Your comments awaiting approval',deleted:'Comment deleted',missing:'Earlier comment unavailable or outside this page',admin:'Moderation',approve:'Approve',hide:'Hide',remove:'Delete text',block:'Block author',unblock:'Unblock author',blocked:'You cannot post comments while your account is blocked.',blocks:'Blocked authors',export:'Export private JSON backup',unlock:'Unlock your interrupted export',mode:'Moderation mode',pre:'New comments await approval (proposed launch mode)',postMode:'Publish new comments immediately',save:'Save settings',confirmMode:'Change moderation mode?',confirmDelete:'Delete this comment’s text? Replies will be retained.',rate:'Please wait at least 60 seconds between submissions.',privacy:'Privacy information',signing:'Signing in…',failedLogin:'Sign-in failed. Please try again.',working:'Working…',confirmExport:'Temporarily freeze all comment and moderation writes to create a complete private backup?',exported:'Complete backup downloaded. Store it privately outside the repository.',blockedMore:'More blocked authors',own:'Signed in as',limit:'Up to 3,000 characters; at least 60 seconds between submissions.',saved:'Saved.'
}:{
 pendingPrivacy:'Видно лише вам і модератору',settingsTitle:'Налаштування обговорення',backupTitle:'Приватні резервні копії',dangerTitle:'Видалення та обмеження доступу',readOnly:'Нові коментарі тимчасово вимкнено.',visibility:'Видимість обговорення',visible:'Видиме',hiddenDiscussion:'Приховане',posting:'Дозволити нові коментарі та відповіді',confirmSettings:'Змінити налаштування обговорення? Статуси наявних коментарів не зміняться.',disabled:'Коментарі поки не увімкнено.',loading:'Завантаження коментарів…',empty:'Опублікованих коментарів поки немає.',error:'Коментарі тимчасово недоступні. Статтю можна читати далі. Щоб спробувати знову, перезавантажте сторінку; перед повторним надсиланням перевірте свої коментарі.',
 login:'Увійти через Google',logout:'Вийти',cancelled:'Вхід скасовано.',post:'Надіслати коментар',text:'Текст коментаря',notice:'Після схвалення коментар буде публічним. Не публікуйте даних пацієнтів і чутливих службових відомостей.',hidden:'Приховано',pending:'Очікує схвалення',sent:'Ваш коментар очікує схвалення.',published:'Коментар опубліковано.',reply:'Відповісти',cancelReply:'Скасувати відповідь',replyTo:'Відповідь для',more:'Завантажити ще',mine:'Ваші коментарі, що очікують схвалення',deleted:'Коментар видалено',missing:'Попередній коментар недоступний або поза цією сторінкою',admin:'Модерація',approve:'Схвалити',hide:'Приховати',remove:'Видалити текст',block:'Заблокувати автора',unblock:'Розблокувати автора',blocked:'Поки ваш обліковий запис заблокований, ви не можете писати коментарі.',blocks:'Заблоковані автори',export:'Експортувати приватну JSON-копію',unlock:'Зняти блокування незавершеного експорту',mode:'Режим модерації',pre:'Нові коментарі очікують схвалення (пропозиція для запуску)',postMode:'Одразу публікувати нові коментарі',save:'Зберегти налаштування',confirmMode:'Змінити режим модерації?',confirmDelete:'Видалити текст коментаря? Відповіді буде збережено.',rate:'Між надсиланнями зачекайте щонайменше 60 секунд.',privacy:'Інформація про приватність',signing:'Вхід…',failedLogin:'Не вдалося увійти. Спробуйте ще раз.',working:'Виконання…',confirmExport:'Тимчасово зупинити записи коментарів і модерації, щоб створити повну приватну копію?',exported:'Повну копію завантажено. Зберігайте її приватно поза репозиторієм.',blockedMore:'Ще заблоковані автори',own:'Ви увійшли як',limit:'До 3000 символів; щонайменше 60 секунд між надсиланнями.',saved:'Збережено.'
};
function node(tag,text='',className=''){const e=document.createElement(tag);e.textContent=text;if(className)e.className=className;return e;}
if(root) start().catch(()=>showFailure());
function showFailure(){root.dataset.state='error';root.setAttribute('aria-busy','false');root.replaceChildren(node('p',strings.error,'comments-status'));root.firstChild.setAttribute('role','alert');}
async function start(){
 root.classList.add('comments-widget');
 if(!commentsConfig.enabled||!commentsConfig.firebase){root.dataset.state='disabled';root.replaceChildren(node('p',strings.disabled));return;}
 root.dataset.state='loading';root.setAttribute('aria-busy','true');root.replaceChildren(node('p',strings.loading));
 const response=await fetch(new URL('../../firebase/article-map.json',import.meta.url),{cache:'no-cache'});if(!response.ok)throw Error('article-map');const map=await response.json();
 const slug=new URL(location.href).searchParams.get('article');const article=map.articles.find(a=>a.slug===slug||a.aliases.includes(slug));if(!article){root.dataset.state='disabled';root.replaceChildren(node('p',strings.disabled));return;}
 const {createCommentsApi}=await import('./api.js');const api=await createCommentsApi(commentsConfig);const settings=await api.settings();
 const section=root.closest('.article-discussion')||root;const discussionHeader=section.querySelector('.article-discussion__header');const adminEntry=new URL(location.href).searchParams.get('commentsAdmin')==='1';
 root.dataset.articleId=article.id;
 const state={user:null,admin:false,blocked:false,items:new Map(),mine:[],review:[],blocks:[],cursor:null,hasMore:false,mineCursor:null,mineMore:false,reviewCursor:null,reviewMore:false,blockCursor:null,blockMore:false,reply:null,busy:false,message:'',generation:0,mode:settings.moderationMode,enabled:settings.enabled,visibility:settings.visibility};
 let textarea,status;
 const button=(text,run)=>{const b=node('button',text);b.type='button';b.disabled=state.busy;b.addEventListener('click',async()=>{await perform(run);if([strings.reply,strings.cancelReply].includes(text))textarea?.focus();});return b;};
 async function perform(run){if(state.busy)return;const active=document.activeElement;const focus=root.contains(active)?{id:active.id,text:active.textContent,commentId:active.closest('[data-comment-id]')?.dataset.commentId}:null;state.busy=true;state.message=strings.working;render();try{await run();if(state.message===strings.working)state.message='';}catch(e){state.message=e.message==='rate-limited'?strings.rate:strings.error;}finally{state.busy=false;render();if(focus&&(document.activeElement===document.body||root.contains(document.activeElement))){const target=focus.id?root.querySelector('#'+CSS.escape(focus.id)):[...root.querySelectorAll('button')].find(b=>b.textContent===focus.text&&b.closest('[data-comment-id]')?.dataset.commentId===focus.commentId);if(target&&!target.disabled)target.focus();else if(textarea)textarea.focus();else{status.tabIndex=-1;status.focus();}}}}
 async function loadPublic(reset=false){if(state.visibility==='hidden'){state.items.clear();state.hasMore=false;return;}const p=await api.page(article.id,{cursor:reset?null:state.cursor});if(reset)state.items.clear();for(const c of p.items)state.items.set(c.id,c);state.cursor=p.cursor;state.hasMore=p.hasMore;}
 async function loadPrivate(kind,reset=false){const generation=state.generation;const cursor=kind==='mine'?state.mineCursor:state.reviewCursor;const p=await api.page(article.id,{cursor:reset?null:cursor,kind});if(generation!==state.generation)return;const key=kind==='mine'?'mine':'review';state[key]=reset?p.items:[...state[key],...p.items];state[key+'Cursor']=p.cursor;state[key+'More']=p.hasMore;}
 async function loadBlocks(reset=false){const generation=state.generation;const p=await api.blockedPage(reset?null:state.blockCursor);if(generation!==state.generation)return;state.blocks=reset?p.items:[...state.blocks,...p.items];state.blockCursor=p.cursor;state.blockMore=p.hasMore;}
 async function moderation(c,action){if(action==='delete'&&!confirm(strings.confirmDelete))return;await api.moderate(c,action);await loadPublic(true);await loadPrivate('review',true);state.message=strings.saved;}
 function comment(c,privateView=false){
  const box=node('article','','comment');box.dataset.commentId=c.id;const header=node('p','','comment-meta');
  header.append(node('strong',c.status==='deleted'?strings.deleted:c.authorName));const time=node('time');if(c.createdAt?.toDate){const date=c.createdAt.toDate();time.dateTime=date.toISOString();time.textContent=new Intl.DateTimeFormat(en?'en-GB':'uk-UA',{dateStyle:'medium',timeStyle:'short'}).format(date);}header.append(' · ',time);box.append(header,node('p',c.status==='deleted'?strings.deleted:c.text,'comment-text'));
  if(privateView){const note=node('p','','comment-state');note.append(node('strong',c.status==='pending'?strings.pending:strings.hidden));if(c.status==='pending')note.append(' · ',strings.pendingPrivacy);box.append(note);}
  const actions=node('div','','comment-actions');
  if(state.enabled&&state.visibility==='visible'&&state.user&&!state.blocked&&c.status==='published'&&c.depth<3)actions.append(button(strings.reply,async()=>{state.reply=c;state.message='';render();textarea?.focus();}));
  if(state.admin&&c.status!=='deleted'&&c.text!==''){
   if(c.status!=='published'){const approve=button(strings.approve,()=>moderation(c,'approve'));approve.classList.add('comments-primary');actions.append(approve);};
   if(c.status!=='hidden')actions.append(button(strings.hide,()=>moderation(c,'hide')));
   const danger=node('div','','comment-danger');danger.setAttribute('role','group');danger.setAttribute('aria-label',strings.dangerTitle);danger.append(button(strings.remove,()=>moderation(c,'delete')),button(strings.block,async()=>{await api.block(c.authorUid,true);await loadBlocks(true);state.message=strings.saved;}));actions.append(danger);
  }
  if(actions.childElementCount)box.append(actions);return box;
 }
 function render(){
  const previousDraft=textarea?.value??'';root.replaceChildren();const hidden=state.visibility==='hidden';section.hidden=hidden&&!state.admin&&!adminEntry;if(discussionHeader)discussionHeader.hidden=hidden;root.dataset.state=hidden?'hidden':'ready';root.setAttribute('aria-busy',String(state.busy));status=node('p',state.message,'comments-status');status.setAttribute('role','status');status.setAttribute('aria-live','polite');root.append(status);
  const authBox=node('div','','comments-auth');
  if(state.user){authBox.append(node('p',`${strings.own} ${state.user.displayName||'Google user'}`),button(strings.logout,async()=>{await api.logout();state.message='';}));}
  else authBox.append(button(strings.login,async()=>{state.message=strings.signing;render();try{await api.login();state.message='';}catch(e){state.message=['auth/popup-closed-by-user','auth/cancelled-popup-request'].includes(e.code)?strings.cancelled:strings.failedLogin;}}));root.append(authBox);
  if(!hidden){
  if(!state.enabled)root.append(node('p',strings.readOnly,'comments-read-only'));
  if(state.enabled&&state.user&&!state.blocked){
   const form=node('form','','comments-form');const label=node('label',strings.text);label.htmlFor='comment-text';textarea=node('textarea');textarea.id='comment-text';textarea.name='comment';textarea.rows=5;textarea.required=true;textarea.maxLength=3000;textarea.disabled=state.busy;textarea.value=previousDraft;textarea.setAttribute('aria-describedby','comments-notice comments-limit');
   if(state.reply)form.append(node('p',`${strings.replyTo}: ${state.reply.authorName}`),button(strings.cancelReply,async()=>{state.reply=null;render();textarea.focus();}));
   const notice=node('p',state.mode==='post'?(en?'Your comment will be public. Do not post patient data or sensitive operational information.':'Ваш коментар буде публічним. Не публікуйте даних пацієнтів і чутливих службових відомостей.'):strings.notice);notice.id='comments-notice';const hint=node('p',strings.limit);hint.id='comments-limit';
   const submit=node('button',strings.post);submit.type='submit';submit.disabled=state.busy;form.append(label,textarea,hint,notice,submit);form.addEventListener('submit',e=>{e.preventDefault();const text=textarea.value.trim();if(!text){textarea.focus();return;}perform(async()=>{const c=await api.post(article.id,text,state.reply);state.reply=null;textarea.value='';if(c.status==='published'){state.items.set(c.id,c);state.message=strings.published;}else{state.mine.unshift(c);state.message=strings.sent;}});});root.append(form);
  }else{textarea=null;if(state.blocked)root.append(node('p',strings.blocked));}
  const list=node('div','','comments-list');
  if(!state.items.size)list.append(node('p',strings.empty));
  const sorted=[...state.items.values()].sort((a,b)=>a.createdAt.seconds-b.createdAt.seconds||a.createdAt.nanoseconds-b.createdAt.nanoseconds||a.id.localeCompare(b.id));const containers=new Map();
  for(const c of sorted){const item=comment(c);const children=node('div','','comment-replies');item.append(children);containers.set(c.id,{item,children});}
  for(const c of sorted){const entry=containers.get(c.id);const parent=containers.get(c.parentId);if(parent)parent.children.append(entry.item);else{if(c.parentId)entry.item.prepend(node('p',strings.missing,'comment-state'));list.append(entry.item);}}
  root.append(list);if(state.hasMore)root.append(button(strings.more,()=>loadPublic()));
  if(state.user&&state.mine.length){root.append(node('h3',strings.mine));for(const c of state.mine)root.append(comment(c,true));}if(state.user&&state.mineMore)root.append(button(strings.more,()=>loadPrivate('mine')));
  const privacy=node('a',strings.privacy);privacy.href=new URL(en?'../../en/policy-en.html':'../../policy.html',import.meta.url).href;root.append(privacy);
  }else{textarea=null;}
  if(state.admin){
   const panel=node('section','','comments-admin');const queue=node('section','','comments-admin-queue');queue.append(node('h3',strings.admin));for(const c of state.review)queue.append(comment(c,true));if(state.reviewMore)queue.append(button(strings.more,()=>loadPrivate('review')));panel.append(queue);const controls=node('section','','comments-admin-settings');controls.append(node('h3',strings.settingsTitle));
   const label=node('label',strings.mode);label.htmlFor='comments-mode';const select=node('select');select.id='comments-mode';for(const[value,text]of[['pre',strings.pre],['post',strings.postMode]]){const option=node('option',text);option.value=value;select.append(option);}select.value=state.mode;select.disabled=state.busy;
   const visibilityLabel=node('label',strings.visibility);visibilityLabel.htmlFor='comments-visibility';const visibility=node('select');visibility.id='comments-visibility';for(const[value,text]of[['visible',strings.visible],['hidden',strings.hiddenDiscussion]]){const option=node('option',text);option.value=value;visibility.append(option);}visibility.value=state.visibility;visibility.disabled=state.busy;
   const postingLabel=node('label',strings.posting);postingLabel.htmlFor='comments-enabled';const posting=node('input');posting.type='checkbox';posting.id='comments-enabled';posting.checked=state.enabled;posting.disabled=state.busy||state.visibility==='hidden';visibility.addEventListener('change',()=>{posting.disabled=state.busy||visibility.value==='hidden';if(visibility.value==='hidden')posting.checked=false;});
   controls.append(visibilityLabel,visibility,postingLabel,posting,label,select,button(strings.save,async()=>{if(!confirm(strings.confirmSettings))return;const next=await api.setSettings({visibility:visibility.value,enabled:posting.checked,moderationMode:select.value});state.mode=next.moderationMode;state.visibility=next.visibility;state.enabled=next.enabled;state.reply=null;await loadPublic(true);state.message=strings.saved;}));
   panel.append(controls);
   panel.append(node('h4',strings.blocks));for(const block of state.blocks){const row=node('div',block.id,'comment-block');row.append(button(strings.unblock,async()=>{await api.block(block.id,false);await loadBlocks(true);state.message=strings.saved;}));panel.append(row);}if(state.blockMore)panel.append(button(strings.blockedMore,()=>loadBlocks()));
   const backups=node('section','','comments-admin-backups');backups.append(node('h3',strings.backupTitle));backups.append(button(strings.export,async()=>{if(!confirm(strings.confirmExport))return;const backup=await api.exportBackup(map);const url=URL.createObjectURL(new Blob([JSON.stringify(backup,null,2)],{type:'application/json'}));const a=node('a');a.href=url;a.download=`comments-backup-${new Date().toISOString().replaceAll(':','-')}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);state.message=strings.exported;}),button(strings.unlock,async()=>{await api.unfreeze();state.message=strings.saved;}));panel.append(backups);root.append(panel);
  }
 }
 await loadPublic();root.setAttribute('aria-busy','false');render();
 api.onAuth(async user=>{const generation=++state.generation;state.user=user;state.admin=false;state.blocked=false;state.mine=[];state.review=[];state.blocks=[];state.mineMore=false;state.reviewMore=false;state.blockMore=false;state.reply=null;textarea=null;render();if(!user)return;try{const[admin,blocked]=await Promise.all([api.isAdmin(),api.isBlocked()]);if(generation!==state.generation)return;state.admin=admin;state.blocked=blocked;if(state.visibility==='visible')await loadPrivate('mine',true);if(admin){await loadPrivate('review',true);await loadBlocks(true);}if(generation===state.generation)render();}catch{if(generation===state.generation){state.message=strings.error;render();}}});
}
