import test from 'node:test';import assert from 'node:assert/strict';
import {deleteApp} from 'firebase-admin/app';import {Timestamp} from 'firebase-admin/firestore';
import {localServices} from '../../tools/comments/local.mjs';import {readCurrent} from '../../tools/comments/restore.mjs';
import {approvedMigration,runControlledMigration} from '../../tools/comments/cloud-privacy-migration.mjs';import {buildDeletionRegister} from '../../js/comments/restore-safety.js';import {decode} from '../../js/comments/backup-format.js';
function fixture(){const time={__type:'timestamp',seconds:1700000000,nanoseconds:123456000},c={articleId:'a-0001',authorUid:'reader',authorName:'Reader',text:'Keep exactly',parentId:null,depth:0,status:'published',createdAt:time,updatedAt:time},records={comments:{parent:c,reply:{...c,parentId:'parent',depth:1,status:'pending',text:'Unpublished reply'}},articles:{'a-0001':{slug:'one',aliases:['one-en']}},moderation:{},blockedUsers:{},rateLimits:{reader:{lastSubmittedAt:time,commentId:'reply'}},admins:{admin:{role:'admin'}},settings:{comments:{enabled:false,visibility:'visible',moderationMode:'pre',schemaVersion:2}},control:{state:{frozen:false,ownerUid:null}}};return {schemaVersion:2,projectId:'demo-controlled-privacy-'+Date.now(),exportedAt:'2026-10-04T00:00:00Z',freezeUsed:true,articleMap:{schemaVersion:1,articles:[{id:'a-0001',slug:'one',aliases:['one-en']}]},records,counts:Object.fromEntries(Object.entries(records).map(([k,v])=>[k,Object.keys(v).length]))};}
async function setup(){const source=fixture(),services=localServices(source.projectId);for(const[name,docs]of Object.entries(source.records))for(const[id,data]of Object.entries(docs))await services.db.doc(name+'/'+id).create(decode(data,Timestamp));return {...services,source,register:buildDeletionRegister(source)};}
async function close(s){await s.db.terminate();await deleteApp(s.app);}
test('controlled migration dry-run is read-only; hash/project approval yields exact atomic pairs and unlock',async()=>{const s=await setup();try{const before=await readCurrent(s.db),dry=await runControlledMigration(s.db,s.source,s.register);assert.equal(dry.dryRun,true);assert.deepEqual(await readCurrent(s.db),before);await assert.rejects(runControlledMigration(s.db,s.source,s.register,{apply:true}),/Explicit project/);assert.deepEqual(await readCurrent(s.db),before);const {target}=approvedMigration(s.source,s.register),out=await runControlledMigration(s.db,s.source,s.register,{apply:true,planSha256:dry.planSha256,confirmProject:s.source.projectId,adminUid:'admin'});assert.equal(out.result,'PASS');assert.equal(out.enabled,false);assert.equal(out.controlUnlocked,true);assert.deepEqual(await readCurrent(s.db),target);assert.equal(target.commentOwners.parent.confirmation,null);assert.equal(target.comments.reply.parentId,'parent');assert.equal(target.comments.reply.status,'pending');await assert.rejects(runControlledMigration(s.db,s.source,s.register),/differs/);}finally{await close(s);}});
test('changed field, extra document or foreign lock stop before writes',async()=>{for(const mutation of [db=>db.doc('comments/parent').update({text:'Changed'}),db=>db.doc('comments/extra').set({new:true}),db=>db.doc('control/state').update({frozen:true,ownerUid:'another-admin'})]){const s=await setup();try{await mutation(s.db);const before=await readCurrent(s.db);await assert.rejects(runControlledMigration(s.db,s.source,s.register,{apply:true,planSha256:approvedMigration(s.source,s.register).plan.planSha256,confirmProject:s.source.projectId,adminUid:'admin'}),/differs/);assert.deepEqual(await readCurrent(s.db),before);}finally{await close(s);}}});
test('wrong approval/admin and unconfigured safety inputs rejected without lock',async()=>{const s=await setup();try{const {plan}=approvedMigration(s.source,s.register);for(const args of [{planSha256:'wrong',adminUid:'admin'},{planSha256:plan.planSha256,adminUid:'unknown'}]){const before=await readCurrent(s.db);await assert.rejects(runControlledMigration(s.db,s.source,s.register,{apply:true,confirmProject:s.source.projectId,...args}));assert.deepEqual(await readCurrent(s.db),before);}const changed=structuredClone(s.source);changed.records.settings.comments.enabled=true;assert.throws(()=>approvedMigration(changed,s.register),/enabled:false/);assert.throws(()=>approvedMigration(s.source,null),/register/);}finally{await close(s);}});

test('atomic size gate and stale deletion history stop before cloud access',()=>{const b=fixture(),root=b.records.comments.parent;b.records.comments=Object.fromEntries(Array.from({length:201},(_,i)=>['c'+i,{...root}]));b.records.rateLimits.reader.commentId='c0';b.counts.comments=201;assert.throws(()=>approvedMigration(b,buildDeletionRegister(b)),/at most 200/);const c=fixture(),reg=buildDeletionRegister(c);reg.comments.parent={articleId:'a-0001',authorUid:'reader',status:'deleted',at:c.records.comments.parent.updatedAt,moderatorUid:'admin'};assert.throws(()=>approvedMigration(c,reg),/requires changes/);});
