/* Local browser integration: actual Auth/Firestore emulators. Only popup transport
 * is replaced with fake Google credentials; this does NOT verify Google OAuth. */
const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs/promises');
const{execFileSync,execFile}=require('node:child_process');
const execFileAsync=require('node:util').promisify(execFile);
const assetCache=new Map();
const base=process.env.COMMENTS_TEST_ORIGIN||'http://127.0.0.1:8133';
if(!/^http:\/\/(127\.0\.0\.1|localhost):\d+$/.test(base))throw Error('Local origin only');
const encode=v=>Buffer.from(JSON.stringify(v)).toString('base64url');
const token=uid=>encode({alg:'none',typ:'JWT'})+'.'+encode({iss:'https://accounts.google.com',aud:'demo-key',sub:uid+'-google',email:uid==='demo-admin'?'admin@example.test':'reader@example.test',email_verified:true,name:uid==='demo-admin'?'Demo admin':'Demo reader',iat:Math.floor(Date.now()/1000),exp:Math.floor(Date.now()/1000)+3600})+'.';
(async()=>{
 const servedConfig=await (await fetch(base+'/js/comments/config.js')).text();
 if(!/projectId["']?\s*:\s*["']demo-serhii-comments["']/.test(servedConfig)||!servedConfig.includes('firestorePort'))throw Error('Refusing browser test: start serve-local.py without --web-config (loopback emulators only)');
 const reset=await fetch('http://127.0.0.1:8080/emulator/v1/projects/demo-serhii-comments/databases/(default)/documents',{method:'DELETE'});if(!reset.ok)throw Error('Cannot reset local demonstration project');
 execFileSync(process.execPath,['tools/comments/seed.mjs'],{stdio:'ignore'});
 const markedPath=process.env.COMMENTS_MARKED_PATH||'/tmp/article-check-marked.js';
 try{await fs.access(markedPath)}catch{execFileSync('curl',['--fail','--silent','--show-error','--max-time','30','--output',markedPath,'https://cdn.jsdelivr.net/npm/marked/marked.min.js']);}
 const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium',args:['--no-sandbox']});
 const out='/tmp/comments-review';await fs.mkdir(out,{recursive:true});let checks=0;
 const check=(value,label)=>{assert.ok(value,label);checks++;};
 async function page(width,fixture=true){const ctx=await browser.newContext({viewport:{width,height:width>600?900:844}});const p=await ctx.newPage();
  await ctx.route(/^https:\/\/(apis\.google\.com|fonts\.googleapis\.com|fonts\.gstatic\.com|cdnjs\.cloudflare\.com)\//,async r=>{
   const url=r.request().url();try{if(!assetCache.has(url))assetCache.set(url,execFileAsync('curl',['--fail','--silent','--show-error','--max-time','30',url],{encoding:'buffer',maxBuffer:10*1024*1024}));const result=await assetCache.get(url);const contentType=url.includes('fonts.googleapis.com')||url.endsWith('.css')?'text/css':url.includes('apis.google.com')?'application/javascript':'application/octet-stream';await r.fulfill({body:result.stdout,contentType});}catch{await r.abort();}
  });
  // Existing Marked asset is cached by the local test runner, not changed in site code.
  const marked=await fs.readFile(markedPath,'utf8');await p.route('**/marked.min.js',r=>r.fulfill({body:marked,contentType:'application/javascript'}));
  if(fixture)await p.route('**/js/comments/api.js*',async r=>{const response=await r.fetch();let body=await response.text();body=body.replace("login:()=>f.signInWithPopup(auth,new f.GoogleAuthProvider())",`login:()=>{if(window.__cancelLogin)return Promise.reject(Object.assign(new Error('cancel'),{code:'auth/popup-closed-by-user'}));return f.signInWithCredential(auth,f.GoogleAuthProvider.credential(window.__fakeToken));}`);await r.fulfill({response,body});});return p;}
 try{
  for(const width of [1280,390,360])for(const lang of ['uk','en']){
   const p=await page(width);const path=lang==='uk'?'/article.html?article=how-kaolin-works':'/en/article-en.html?article=how-kaolin-works-en';await p.goto(base+path+'&commentsEmulator=1');await p.locator('#comments[data-state=ready]').waitFor();
   check(await p.locator('#comments').getAttribute('data-article-id')==='a-0001','shared language article ID');check(await p.locator('.comments-list > .comment').count()===20,'first page bounded');
   check(await p.locator('#comments').innerText().then(t=>t.includes('<img src=x onerror=')),'HTML is literal text');check(await p.locator('#comments img').count()===0,'no injected image');
   await p.locator('#comments button').filter({hasText:lang==='uk'?'Завантажити ще':'Load more'}).click();await p.locator('[data-comment-id=demo-reply]').waitFor();check(await p.locator('[data-comment-id=demo-00] [data-comment-id=demo-reply]').count()===1,'nested reply');check(await p.locator('[data-comment-id=demo-reply] [data-comment-id=demo-depth-3]').count()===1,'maximum depth thread retained');
   await p.evaluate(()=>{window.__cancelLogin=true});await p.locator('.comments-auth button').click();await p.getByText(lang==='uk'?'Вхід скасовано.':'Sign-in was cancelled.',{exact:true}).waitFor();check(true,'cancelled UI');
   await p.evaluate(t=>{window.__cancelLogin=false;window.__fakeToken=t},token('demo-reader'));await p.locator('.comments-auth button').click();await p.locator('#comment-text').waitFor();await p.getByText(lang==='uk'?'Ваші коментарі, що очікують схвалення':'Your comments awaiting approval',{exact:true}).waitFor();
   await p.locator('[data-comment-id=demo-00] > .comment-actions button').first().focus();await p.keyboard.press('Enter');await p.waitForFunction(()=>document.activeElement?.id==='comment-text');check(true,'keyboard reply focuses input');
   await p.locator('#comment-text').fill('Keyboard and narrow screen demonstration. '+ 'long-text-'.repeat(15));check(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'no horizontal page scrolling');
   await p.evaluate(()=>scrollTo(0,document.querySelector('#comments').getBoundingClientRect().top+scrollY-140));await p.screenshot({path:out+'/'+lang+'-'+width+'.png'});
   await p.locator('.comments-auth button').click();await p.locator('.comments-auth button').filter({hasText:lang==='uk'?'Увійти через Google':'Sign in with Google'}).waitFor();check(await p.locator('#comment-text').count()===0,'logout removes composer');await p.context().close();
  }
  const p=await page(390);await p.goto(base+'/article.html?article=medical-app-without-internet&commentsEmulator=1');await p.locator('#comments[data-state=ready]').waitFor();check((await p.locator('#comments').innerText()).includes('Опублікованих коментарів поки немає.'),'empty discussion');
  await p.evaluate(t=>window.__fakeToken=t,token('demo-reader'));await p.locator('.comments-auth button').click();await p.locator('#comment-text').fill('Local pending comment');await p.locator('.comments-confirmation input').check();await p.locator('.comments-form button[type=submit]').click();await p.getByText('Ваш коментар очікує схвалення.',{exact:true}).waitFor();check(await p.locator('.comments-list .comment').count()===0,'pending not public');
  await p.locator('#comment-text').fill('Too soon');await p.locator('.comments-confirmation input').check();await p.locator('.comments-form button[type=submit]').click();await p.getByText('Між надсиланнями зачекайте щонайменше 60 секунд.',{exact:true}).waitFor();check(true,'visible rate limit');const translatedLink=await p.locator('.site-nav__language-option[lang=en]').getAttribute('href');check(translatedLink.includes('medical-app-without-internet'),'language link points to same article');const translatedUrl=new URL(translatedLink,p.url());translatedUrl.searchParams.set('commentsEmulator','1');await p.goto(translatedUrl.href);await p.locator('#comments[data-state=ready]').waitFor();await p.getByText('Local pending comment',{exact:true}).waitFor();check(await p.locator('#comments').getAttribute('data-article-id')==='a-0004','actual posted comment is shared with EN translation');await p.context().close();
  const admin=await page(360);await admin.goto(base+'/en/article-en.html?article=how-kaolin-works-en&commentsEmulator=1');await admin.locator('#comments[data-state=ready]').waitFor();await admin.evaluate(t=>window.__fakeToken=t,token('demo-admin'));await admin.locator('.comments-auth button').click();await admin.locator('.comments-admin').waitFor();check(await admin.locator('#comments-mode').inputValue()==='pre','proposed premoderation');check(await admin.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'admin mobile has no overflow');await admin.locator('[data-comment-id=demo-pending]').last().getByRole('button',{name:'Approve',exact:true}).click();await admin.getByRole('button',{name:'Load more',exact:true}).click();await admin.locator('.comments-list [data-comment-id=demo-pending]').waitFor();check(true,'admin approves pending');await admin.locator('.comments-list [data-comment-id=demo-pending]').getByRole('button',{name:'Hide',exact:true}).click();await admin.locator('.comments-admin [data-comment-id=demo-pending]').waitFor();check(await admin.locator('.comments-list [data-comment-id=demo-pending]').count()===0,'admin hides publication');await admin.locator('.comments-admin [data-comment-id=demo-pending]').getByRole('button',{name:'Block author',exact:true}).click();await admin.locator('.comment-block').filter({hasText:'demo-reader'}).waitFor();check(true,'author block displayed');await admin.locator('.comment-block').filter({hasText:'demo-reader'}).getByRole('button',{name:'Unblock author',exact:true}).click();await admin.locator('.comment-block').filter({hasText:'demo-reader'}).waitFor({state:'detached'});check(true,'author unblocked');await admin.evaluate(()=>scrollTo(0,document.querySelector('.comments-admin').getBoundingClientRect().top+scrollY-100));await admin.screenshot({path:out+'/en-admin-360.png'});await admin.context().close();
  const realPopup=await page(390,false);await realPopup.goto(base+'/article.html?article=group-medical-bag&commentsEmulator=1');await realPopup.locator('#comments[data-state=ready]').waitFor();let opened=realPopup.waitForEvent('popup');await realPopup.locator('.comments-auth button').click();let popup=await opened;await popup.getByText('Demo reader',{exact:false}).waitFor();await popup.close();await realPopup.getByText('Вхід скасовано.',{exact:true}).waitFor({timeout:20000});check(true,'actual emulator popup cancellation');opened=realPopup.waitForEvent('popup');await realPopup.locator('.comments-auth button').click();popup=await opened;await popup.getByText('Demo reader',{exact:false}).click();await realPopup.locator('#comment-text').waitFor();check(true,'actual emulator popup Google-provider login');await realPopup.locator('.comments-auth button').click();await realPopup.getByRole('button',{name:'Увійти через Google',exact:true}).waitFor();check(true,'actual emulator logout');await realPopup.context().close();
  for(const lang of ['uk','en']){
   const fail=await page(360,false);await fail.route('http://127.0.0.1:8080/**',r=>r.abort('failed'));const path=lang==='uk'?'/article.html?article=hospital-capabilities':'/en/article-en.html?article=hospital-capabilities';await fail.goto(base+path+'&commentsEmulator=1');await fail.locator('#comments[data-state=error]').waitFor({timeout:20000});check(await fail.locator('#articleContent').innerText().then(t=>t.length>1000),'article works with blocked Firestore');check(await fail.locator('.site-nav__language-switcher a').count()>=2,'language links survive');await fail.context().close();const quota=await page(390,false);await quota.route('**/js/comments/api.js*',r=>r.fulfill({body: `export async function createCommentsApi(){return {settings:async()=>{throw Object.assign(new Error('quota'),{code:'resource-exhausted'})}}}`,contentType:'application/javascript'}));await quota.goto(base+path+'&commentsEmulator=1');await quota.locator('#comments[data-state=error]').waitFor();check(await quota.locator('#articleContent').innerText().then(t=>t.length>1000),'article works with simulated quota error');await quota.context().close();
   const disabled=await page(390,false);let firebase=false;disabled.on('request',r=>{if(/firebase-sdk|8080|9099|googleapis.com.*(firestore|identitytoolkit)/.test(r.url()))firebase=true});await disabled.goto(base+path);await disabled.locator('#comments[data-state=disabled]').waitFor();check(!firebase,'disabled does not load SDK or Firebase');await disabled.context().close();
  }
  console.log(JSON.stringify({checks,result:'passed',screenshots:out,googleOAuth:'Actual Auth Emulator popup and fake Google-provider credentials tested; real Google OAuth NOT TESTED'},null,2));
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1});
